language: java
sudo: required
env:  
  global:
    secure: IkFdstJ37AIIUx/GUTwV3gPpRU3CY4uV40AyxSfLur1ADTcx58cjngkJ+Gou9FcOrOb3dCzQiky5zUjqk1VoHnSQp34Isq/fOr9pMD+6M4v1Sv2Ymk/SY3Scp/rWRLbz6GUj2KqrWfhEGat2tk7ZAFGaTnjdVhSAb9LbDqWS+htXN6DiVEDhA0SBxxLFPYQbfTMiHH1o7hCcQ86jfJ8DQTKEvzRDolLQ6U1sZni4AgyfK4oRWJWgDp+r0Rawadpgc6jI3HV3e6qF6DZvYhIADcV3PoH6qK4XHLz1imcgw4o1bi1K/rKXyY12ZICIheEu7eo+sx+y5jvgB7Tt6TaobPKDFTICHtvsqCeYhTWmDFfJc8qM+p4NXYg9Py34K+frHOTai443E3+xjA/RTfr2WQ4FiT4aM5/5yK3NtLGo60ULjJ72sqY5SPREWxYgaXDs/diA5ffyUxRunw5fr/8HrvC43w/YJZUonObCo/Aapm+nmuGlrNXRR7T0eSWPGDNq6BzYjt8UZrQBKSUGplTdHl02CFfgTPcz51YcjtHnIpyLCxMxw0RtAt0SggWzT+TlVZ1OfQ4Wr5z2VNGUhGXQJjTk7wXw/p2rkIV+3pMr6alHxrKSAjdBgjupP8OtrpVdKws/050kG3vGFjvTlfm08gb0YIxYp9ZCCnX+yiyZbGQ=
addons:
  chrome: stable
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - gradle run &
  - sleep 10
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10
script:
  - gradle check
notifications:
  email: false
after_success:
  - "echo $TRAVIS_PULL_REQUEST"
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/Ouzii/ohtuMiniprojektiTeamPollot/development/travis-merge.sh"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^devel' BRANCH_TO_MERGE_INTO=master GITHUB_REPO='Ouzii/OhtuMiniprojektiTeamPollot' /tmp/travis-automerge"


