language: java
sudo: required
env: DISPLAY=':99.0'
addons:
  chrome: stable
before_install:
  - gradle run &
  - sleep 10
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  
  - sleep 10
script:
  - gradle check
  - whereis google-chrome-stable
  - whereis chromedriver
notifications:
  email: false
